config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  get "dashboard", to: "dashboard#index"

  # Defines the root path route ("/")
  root "home#index"

  resources :boards do
    resources :lists, except: :show
    resources :board_users, only: [:new, :create]
  end

  resources :lists do
    resources :items
  end

  namespace :api do
    resources :boards do
      resources :lists, only: :index, controller: "lists"
      resources :list_positions, only: [:index, :update], controller: "list_positions"
    end
    put "item_positions", to: "item_positions#update"

    resources :items, only: :show
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user

  validates :name, presence: true

  has_many :lists, dependent: :destroy

  has_many :board_users, dependent: :destroy
  has_many :members, through: :board_users, source: :user

  after_create :assign_user_as_member
  def assign_user_as_member
    members << user
  end
end

app/models/board_user.rb
class BoardUser < ApplicationRecord
  belongs_to :board
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list

  validates :title, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board

  has_many :items, dependent: :destroy

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, dependent: :destroy
end

app/controllers/api/item_positions_controller.rb
module Api
  class ItemPositionsController < ApplicationController
    protect_from_forgery with: :null_session

    def update
      items = items_params[:items].map do |item_data|
        item = Item.find(item_data[:id])
        item.position = item_data[:position]
        item.list_id = item_data[:list_id]
        item
      end

      Item.import items, on_duplicate_key_update: { conflict_target: [:id], columns: [:position, :list_id] }
      render json: ItemSerializer.new(items).serializable_hash.to_json
    end

    private

    def items_params
      params.permit(items: [:id, :position, :list_id])
    end
  end
end

app/controllers/api/items_controller.rb
module Api
  class ItemsController < ApplicationController
    protect_from_forgery with: :null_session

    def show
      item = Item.find(params[:id])

      render json: ItemSerializer.new(item).serializable_hash.to_json
    end
  end
end

app/controllers/api/list_positions_controller.rb
module Api
  class ListPositionsController < ApplicationController
    protect_from_forgery with: :null_session

    def update
      lists = board.lists.to_a
      delete_index = lists.index { |list| list.id == params[:id].to_i }
      list = lists.delete_at(delete_index)
      lists.insert(params[:position].to_i, list)
      lists.each_with_index do |list, index|
        list.position = index
      end

      List.import lists, on_duplicate_key_update: { conflict_target: [:id], columns: [:position] }

      render json: ListSerializer.new(lists).serializable_hash.to_json
    end

    private

    def board
      @board ||= Board.find(params[:board_id])
    end
  end
end

app/controllers/api/lists_controller.rb
module Api
  class ListsController < ApplicationController
    protect_from_forgery with: :null_session

    def index
      @lists = board.lists.order(position: :asc)

      render json: ListSerializer.new(@lists).serializable_hash.to_json
    end

    private

    def board
      @board ||= Board.find(params[:board_id])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization 
end

app/controllers/board_users_controller.rb
class BoardUsersController < ApplicationController
  before_action :authenticate_user!

  def new
    @board_user = board.board_users.new
  end

  def create
    board_user_ids = board.members.where.not(id: board.user_id).ids

    user_ids_to_destroy = board_user_ids - user_ids

    BoardUser.where(board: board, user_id: user_ids_to_destroy).delete_all
    users_to_assign = User.where(id: user_ids)
    board.members << users_to_assign
    redirect_to board_path(board)
  end

  private

  def user_ids
    params[:user_ids].map(&:to_i).reject(&:zero?)
  end

  def board
    @board ||= Board.find(params[:board_id])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!

  def new
    @board = Board.new
  end

  def edit
    authorize board
  end

  def show
    authorize board
  end

  def create
    @board = Board.new(board_params.merge(user: current_user))
    
    if @board.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    authorize board

    if board.update(board_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    authorize board
    board.destroy
    redirect_to root_path
  end

  private

  def board_params
    params.require(:board).permit(:name)
  end 

  def board
    @board ||= Board.find(params[:id])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @boards = Board.order(:created_at)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to dashboard_path if user_signed_in?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

  protect_from_forgery with: :null_session

  def new
    @item = list.items.new
  end

  def edit
    @item = list.items.find(params[:id])
  end

  def create
    @item = list.items.new(item_params)

    if @item.save
      redirect_to board_path(list.board)
    else
      render :new
    end
  end

  def update
    @item = list.items.find(params[:id])

    if @item.update(item_params)
      redirect_to board_path(list.board)
    else
      render :edit
    end
  end

  def destroy
    @item = list.items.find(params[:id])
    @item.destroy
    respond_to do |format|
      format.json do
        render json: {}, status: 200
      end
    end
  end

  private

  def list
    @list ||= List.find(params[:list_id])
  end

  def item_params
    params.require(:item).permit(:title, :description)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!

  protect_from_forgery with: :null_session, only: :destroy

  def new
    @list = board.lists.new
  end

  def edit
    @list = board.lists.find(params[:id])
  end

  def create
    @list = board.lists.new(list_params)

    if @list.save
      redirect_to board_path(board)
    else
      render :new
    end
  end

  def update
    @list = board.lists.find(params[:id])

    if @list.update(list_params)
      redirect_to board_path(board)
    else
      render :edit
    end
  end

  def destroy
    @list = board.lists.find(params[:id])
    @list.destroy
    respond_to do |format|
      format.json do
        render json: {}, status: 200
      end
    end
  end

  private

  def board
    @board ||= Board.find(params[:board_id])
  end

  def list_params
    params.require(:list).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/board_users/new.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
  <div class="mx-auto max-w-3-xl">
    <div class="bg-white mt-12 px-8 py-12 rounded-xl drop-shadow-lg">
      <%= form_with url: board_board_users_path(@board), scope: nil, local: true, class: "space-y-8 divide-gray-200" do |f| %>
        <div class="space-y-8 divide-y divide-gray-200" style="margin-top: 0">
          <div>
            <div class="mb-5">
              <h3 class="text-lg font-medium leading-6 text-gray-900">Board Member List</h3>
              <p class="mt-1 text-sm text-gray-500">This form adds/removes board members.</p>
            </div>
            <fieldset>
              <legend class="text-lg font-medium text-gray-900">Members</legend>
              <div class="mt-4 divide-y divide-gray-200 border-t border-b border-gray-200">
                <% User.find_each do |user| %>
                  <div class="relative flex items-start py-4">
                    <div class="min-w-0 flex-1 text-sm">
                      <%= f.label :user_ids, class: "select-none font-medium text-gray-700" do %>
                        <%= user.email %>
                      <% end %>
                    </div>
                    <div class="ml-3 flex h-5 items-center">
                      <%= f.check_box "user_ids[]", { class: "h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500", miltiple: true, checked: @board.members.include?(user), disabled: @board.user == user }, user.id  %>
                    </div>
                  </div>
                <% end %>
              </div>
            </fieldset>
        </div>

        <div class="mt-6 flex items-center justify-end gap-x-6">
          <%= link_to "Cancel", root_path, class: "text-sm font-semibold leading-6 text-gray-900" %>
          <%= f.submit "Assign Members", class: "cursor-pointer rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/boards/_form.html.erb
<div class="bg-white mt-12 px-8 py-12 rounded-xl drop-shadow-lg">
  <%= form_with model: board, local: true, class: "space-y-8 divide-gray-200" do |f| %>
    <div class="space-y-12" style="margin-top: 0">
      <div class="border-b border-gray-900/10 pb-12">
        <% if board.new_record? %>
          <h2 class="text-base font-semibold leading-7 text-gray-900">New Board</h2>
          <p class="mt-1 text-sm leading-6 text-gray-600">This form creates a new board.</p>
        <% else %>
          <h2 class="text-base font-semibold leading-7 text-gray-900">Edit Board</h2>
          <p class="mt-1 text-sm leading-6 text-gray-600">This form edits a board.</p>
        <% end %>

        <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
          <div class="sm:col-span-6">
            <%= f.label :name, class: "block text-sm font-medium leading-6 text-gray-900" %>
            <div class="mt-2">
              <%= f.text_field :name, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>             
            </div>
          </div>
        </div>
    </div>

    <div class="mt-6 flex items-center justify-end gap-x-6">
      <%= link_to "Cancel", root_path, class: "text-sm font-semibold leading-6 text-gray-900" %>
      <%= f.submit class: "cursor-pointer rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
    </div>
  <% end %>
</div>

app/views/boards/edit.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 ">
  <div class="mx-auto max-w-3xl">
    <%= render "form", board: @board %>
  </div>
</div>

app/views/boards/new.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 ">
  <div class="mx-auto max-w-3xl">
    <%= render "form", board: @board %>
  </div>
</div>

app/views/boards/show.html.erb
<div class="mx-auto max-w-full px-24 py-12">
  <div class="mb-5">
    <%= link_to "Add New Member", new_board_board_user_path(@board), class: "inline-flex items-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
  </div>
  <div 
    data-controller="board" 
    class="mx-auto max-w-full" 
    data-api-url="<%= api_board_lists_path(@board) %>" 
    data-list-positions-api-url="<%= api_board_list_positions_path(@board) %>"
    data-board-lists-url="<%= board_lists_path(@board) %>"
    data-item-positions-api-url="<%= api_item_positions_path %>"
    id="board" 
    style="overflow-x: auto;"
  >
  </div>
</div>

<%= render "shared/modal" %>

app/views/dashboard/index.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-12">
  <div class="mx-auto max-w-4xl">
    <ul role="list" class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
      <% @boards.each do |board| %>
        <li class="col-span-1 divide-y divide-gray-200 rounded-lg bg-white shadow">
          <div class="flex w-full items-center justify-between space-x-6 p-6">
            <div class="flex-1 truncate">
              <div class="flex items-center space-x-3">
                <h3 class="truncate text-sm font-medium text-gray-900"><%= link_to board.name, board_path(board), class: "link" %></h3>
              </div>
            </div>
          </div>
          <div>
            <div class="-mt-px flex divide-x divide-gray-200">
              <div class="flex w-0 flex-1">
                <%= link_to edit_board_path(board), class: "relative -mr-px inline-flex w-0 flex-1 items-center justify-center rounded-bl-lg border border-transparent py-4 text-sm font-medium text-gray-700 hover:text-gray-500" do %>
                  <span class="ml-3">Edit</span>
                <% end %>
              </div>
              <div class="-ml-px flex w-0 flex-1">
                <%= link_to board_path(board), data: { "turbo-method": :delete }, class: "relative inline-flex w-0 flex-1 items-center justify-center rounded-br-lg border border-transparent py-4 text-sm font-medium text-gray-700 hover:text-gray-500" do %>
                  <span class='ml-3 text-red-700'>Delete</span>
                <% end %>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/items/_form.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 ">
  <div class="mx-auto max-w-3xl">
    <div class="bg-white mt-12 px-8 py-12 rounded-xl drop-shadow-lg">
      <%= form_with model: [list, item], local: true, class: "space-y-8 divide-gray-200" do |f| %>
        <div class="space-y-12" style="margin-top: 0">
          <div class="border-b border-gray-900/10 pb-12">
            <% if item.new_record? %>
              <h2 class="text-base font-semibold leading-7 text-gray-900">New Item</h2>
              <p class="mt-1 text-sm leading-6 text-gray-600">This form creates a new item.</p>
            <% else %>
              <h2 class="text-base font-semibold leading-7 text-gray-900">Edit <%= item.title %></h2>
              <p class="mt-1 text-sm leading-6 text-gray-600">This form edits an item.</p>
            <% end %>

            <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
              <div class="sm:col-span-6">
                <%= f.label :title, class: "block text-sm font-medium leading-6 text-gray-900" %>
                <div class="mt-2">
                  <%= f.text_field :title, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>             
                </div>
              </div>
            </div>
            <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
              <div class="sm:col-span-6">
                <%= f.label :description, class: "block text-sm font-medium leading-6 text-gray-900" %>
                <div class="mt-2">
                  <%= f.text_area :description, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>             
                </div>
              </div>
            </div>
        </div>

        <div class="mt-6 flex items-center justify-end gap-x-6">
          <%= link_to "Cancel", root_path, class: "text-sm font-semibold leading-6 text-gray-900" %>
          <%= f.submit class: "cursor-pointer rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/items/edit.html.erb
<%= render "form", list: @list, item: @item%>

app/views/items/new.html.erb
<%= render "form", list: @list, item: @item%>

app/views/layouts/_header.html.erb
<nav class="bg-gray-800">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button-->
        <button type="button" class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="absolute -inset-0.5"></span>
          <span class="sr-only">Open main menu</span>
          <!--
            Icon when menu is closed.

            Menu open: "hidden", Menu closed: "block"
          -->
          <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <!--
            Icon when menu is open.

            Menu open: "block", Menu closed: "hidden"
          -->
          <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex flex-shrink-0 items-center">
          <img class="h-8 w-auto" src="https://tailwindui.com/plus/img/logos/mark.svg?color=indigo&shade=600" alt="Your Company">
        </div>
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <% if user_signed_in? %>
              <%= link_to "Dashboard", root_path, class: "#{"bg-gray-900" if controller_name == "dashboard"} text-white rounded-md px-3 py-2 text-sm font-medium"%>
              <%= link_to "Log Out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" %>
            <% end %>
          </div>
        </div>
        <div class="flex items-center ml-auto">
          <% if user_signed_in? %>
            <div class="flex-shrink-0">
              <% if controller_name == "boards" && action_name == "show" %>
                  <%= link_to new_board_list_path(@board), class: "relative inline-flex items-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700" do %>
                    <!-- Heroicon name: mini/plus -->
                    <svg class="=ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path d="M10.75 4.75a.75.75 0 00-1.5 0v4.5h-4.5a.75.75 0 000 1.5h4.5v4.5a.75.75 0 001.5 0v-4.5h4.5a.75.75 0 000-1.5h-4.5v-4.5z" />
                    </svg>
                    <span>New List</span>
                  <% end %>
              <% else %>
                  <%= link_to new_board_path, class: "relative inline-flex items-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700" do %>
                    <!-- Heroicon name: mini/plus -->
                    <svg class="=ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path d="M10.75 4.75a.75.75 0 00-1.5 0v4.5h-4.5a.75.75 0 000 1.5h4.5v4.5a.75.75 0 001.5 0v-4.5h4.5a.75.75 0 000-1.5h-4.5v-4.5z" />
                    </svg>
                    <span>New Board</span>
                  <% end %>
              <% end %>
            </div>
      </div>
        </div>
      </div>
      <% else %>
      <div class="ml-4 flex flex-shrink-0 items-center">
        <%= link_to "Register", new_user_registration_path, class: "link" %>
        <%= link_to "Log In", new_user_session_path, class: "ml-3 link" %>
      </div>
     <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KanbanBoard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-400">
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 ">
  <div class="mx-auto max-w-3xl">
    <div class="bg-white mt-12 px-8 py-12 rounded-xl drop-shadow-lg">
      <%= form_with model: [board, list], local: true, class: "space-y-8 divide-gray-200" do |f| %>
        <div class="space-y-12" style="margin-top: 0">
          <div class="border-b border-gray-900/10 pb-12">
            <% if @list.new_record? %>
              <h2 class="text-base font-semibold leading-7 text-gray-900">New List</h2>
              <p class="mt-1 text-sm leading-6 text-gray-600">This form creates a new list.</p>
            <% else %>
              <h2 class="text-base font-semibold leading-7 text-gray-900">Edit <%= list.title %></h2>
              <p class="mt-1 text-sm leading-6 text-gray-600">This form edits a list.</p>
            <% end %>

            <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
              <div class="sm:col-span-6">
                <%= f.label :title, class: "block text-sm font-medium leading-6 text-gray-900" %>
                <div class="mt-2">
                  <%= f.text_field :title, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>             
                </div>
              </div>
            </div>
        </div>

        <div class="mt-6 flex items-center justify-end gap-x-6">
          <%= link_to "Cancel", root_path, class: "text-sm font-semibold leading-6 text-gray-900" %>
          <%= f.submit class: "cursor-pointer rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/edit.html.erb
<%= render "form", board: @board, list: @list %>

app/views/lists/new.html.erb
<%= render "form", board: @board, list: @list %>

app/views/shared/_modal.html.erb
<div
  data-controller="modal"
  id="modal-wrapper"
  class="hidden relative z-10"
  aria-labelledby="modal-title"
  role="dialog"
  aria-modal="true"
>
  <div class="hidden" id="show-modal-div" data-action="click->modal#showModal"></div>
  <div
    id="modal-backdrop"
    class="hidden fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"
    data-transition-enter="ease-out duration-300"
    data-transition-enter-start="opacity-0"
    data-transition-enter-end="opacity-100"
    data-transition-leave="ease-in duration-200"
    data-transition-leave-start="opacity-100"
    data-transition-leave-end="opacity-0"
  ></div>
  <div class="fixed z-10 inset-0 overflow-y-auto">
    <div class="flex items-end sm:items-center justify-center min-h-full p-4 text-center sm:p-0">
      <div
        id="modal-panel"
        class="hidden relative bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:w-full sm:max-w-lg"
        data-transition-enter="ease-out duration-300"
        data-transition-enter-start="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
        data-transition-enter-end="opacity-100 translate-y-0 sm:scale-100"
        data-transition-leave="ease-in duration-200"
        data-transition-leave-start="opacity-100 translate-y-0 sm:scale-100"
        data-transition-leave-end="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
      >
        <div class="flex mb-5">
          <div class="flex-none cursor-pointer" data-modal-target="closeButton">
            <svg  xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <%# <path fill-rule="evenodd" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" /> %>
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
            </svg>
          </div>
        </div>
        <div>
          <p class="font-bold tracking-wide">Title:</p>
          <p id="item-title" class="tracking-wide mb-5"></p>

          <p class="font-bold tracking-wide">Description:</p>
          <p id="item-description" class="tracking-wide mb-5"></p>

          <div class="flex">
            <div><%= link_to "Edit", "", class: "link", id: "item-edit-link" %></div>
            <div class="ml-4"><%= link_to "Delete", "", class: "link", style: "color: red;", id: "item-delete-link", data: { turbo_method: :delete } %></div>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>